# Generated by Django 4.1.4 on 2023-01-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_create_article_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.TextField(blank=True),
        ),
    ]
